### ISSUE TITLE
ModuleNotFoundError: No module named 'network_confv6'

### ISSUE THREAD

**Issue by ghost** [yaoxuefeng6/Paddle_baseline_KDD2019#1]
First, thank you for sharing these beautiful baseline codes. 
I have successfully installed paddle paddle. When I ran "python local_train.py", it printed the following error.

Traceback (most recent call last):
  File "local_train.py", line 7, in <module>
    from network_confv6 import ctr_deepfm_dataset
ModuleNotFoundError: No module named 'network_confv6'

I read your description mentioned to download the .whl files. Could you explain more about what files need to be download/clone on the develop branch of paddle paddle? Thank you!

**Comment by Rayman96** [comment]
network_confv6.py is being contained in the folder "networks". You can register the path into your system, or move the netwrok_confv6.py out of the folder into the same level as local_train.py

**Comment by ghost** [comment]
@Rayman96 Thank you very much!
