### ISSUE TITLE
Two little spelling mistakes

### ISSUE THREAD

**Issue by LeoCQ707** [yaoxuefeng6/Paddle_baseline_KDD2019#3]
There may be two little spelling mistake in README.md. The first one is in the second line of the second paragraph which says "solove the task". Maybe it should be "solve the task" instead? The second one is in the last line of the part "preprocess feature" which says "gengerted from open weather record". Maybe it should be "generated from open weather record" instead?

**Comment by yaoxuefeng6** [comment]
Many thanks for the comments. It is my bad and sorry for the confusion. I have went through all spellings again and modify them correspondingly.
