### ISSUE TITLE
Score issue

### ISSUE THREAD

**Issue by AliOsm** [yaoxuefeng6/Paddle_baseline_KDD2019#7]
After training the model for 10 epochs and predicting the results using the 10th model the score is 29.09 only, any ideas?

**Comment by yaoxuefeng6** [comment]
Hi, I dont know what is the "score". Maybe you are doing some offline validation. However, in this baseline using default codes, the training would largely converage after one epoch. The online test score shoule be 0.68+.

**Comment by yaoxuefeng6** [comment]
Hi, I dont know what is the "score". Maybe you are doing some offline validation. However, in this baseline using default codes, the training would largely converage after one epoch. The online test score shoule be 0.68+. To get a better "score", please try to do more powerful feature engineering, or  try other recommendation networks in networks folder.

**Comment by AliOsm** [comment]
Actually, I'm talking about the online scoring system, after training the model for 10 epochs and predict the test set results using the last checkpoint the score was 29.09.

BTW, there are some bugs in the code, like the `build_submit.py` file why it is opens the csv file in `wb` mode not `r`, and it is predicting almost all outputs to zeros.

Is there something wrong?

**Comment by yaoxuefeng6** [comment]
'wb' is because we need to write a result file for submitting. I dont think there is a bug here.
The number of zeros is relative to the variable THRESHOLD_LABEL in preprocess_dense.py. There should be very little zeros from default codes. Please double check you run the right/latest pulled codes.

**Comment by AliOsm** [comment]
Hello, I've pulled the code from the repository then I did the following:
- Run `python preprocess_dense.py` to prepare train data
- Run `python pre_test_dense.py` to prepare test data
- Run `split -a 2 -d -l 200000 normed_train.txt normed_train` to split train data
- Run `python local_train.py` to start training, but the following error appears: `ValueError: the output of process() must be in list or tuple type` and to solve it I've converted the line 137 from file `map_reader.py` from: `yield zip(feature_name, [dense_feature] + sparse_feature + [sparse_feature_fm] + [label])` to `yield `<b>`list(`</b>`zip(feature_name, [dense_feature] + sparse_feature + [sparse_feature_fm] + [label])`<b>`)`</b> and rerun `python local_train.py`
- Train for 1 epoch
- Run `python generate_test.py`
- Run `python build_submit.py`, the following error appears: `TypeError: a bytes-like object is required, not 'str'` and to solve it I've converted the line 8 from file `build_submit.py` from: `with io.open('./submit/submit.csv', 'wb') as csv_file:` to `with io.open('./submit/submit.csv', '`<b>`w`</b>`') as csv_file:` and rerun `python build_submit.py`
- Submit the created file to the online system and get 18.09 as result
Any comment?
Thanks

**Comment by yaoxuefeng6** [comment]
About the ValyeError in local_train.py, Please try to run the codes in Linux. Or, if you change the input format to list, may be you need to change the format of testing to list, too.

**Comment by p1397603** [comment]
I run the codes in Linux, but still encounter the ValueError: the output of process() must be in list or tuple type. How can I solve it?
